name: Employeurs
main: fr.harmo.Employeurs.Employeurs
version: 0.8
author: Harmo
softdepend: [Vault]
commands:
    emp:
        description: Commande de base pour les joueurs
        usage: /emp
    empadm:
        description: Commande de base pour les admins
        usage: /empadm
permissions:
    emp.list:
        description: Affiche la liste des emplois disponibles
        default: true
    emp.use:
        description: Permet l utilisation du plugin
        default: true
    emp.create:
        description: Permet de creer les offres d'emploi
        default: true
    emp.admin.add:
        description: Ajoute un metier en database
        default: op